Added lpa

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -6,20 +6,20 @@ workflows:
         script: npm install
       - name: "Ionic Ios Build"
         script: ionic capacitor build ios
-      - name: "Add provisioning profiles"
-        script: |
-          set -e # exit on first failed command
-          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
-          mkdir -p "$PROFILES_HOME"
-          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
-      - name: "Add signing certificate"
-        script: |
-          set -e # exit on first failed command
-          echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
-          keychain initialize
-          keychain add-certificates \
-              --certificate /tmp/certificate.p12 \
-              --certificate-password "${CERTIFICATE_PASSWORD?}"
+      # - name: "Add provisioning profiles"
+      #   script: |
+      #     set -e # exit on first failed command
+      #     PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
+      #     mkdir -p "$PROFILES_HOME"
+      #     echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
+      # - name: "Add signing certificate"
+      #   script: |
+      #     set -e # exit on first failed command
+      #     echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
+      #     keychain initialize
+      #     keychain add-certificates \
+      #         --certificate /tmp/certificate.p12 \
+      #         --certificate-password "${CERTIFICATE_PASSWORD?}"
       - name: "Increment build number"
         script: agvtool new-version -all $BUILD_NUMBER
       - name: "Set up code signing settings on Xcode project"
